### ISSUE TITLE
install 

### ISSUE THREAD

**Issue by BurlyLuo** [wrfly/k8s-install.sh#1]
Hello
First ：
cat > /etc/docker/daemon.json <<EOF
{
  "registry-mirrors": ["https://m.mirror.aliyuncs.com"],
  "insecure-registries" : ["quay-io.mirror.kfd.me", "k8s-gcr.mirror.kfd.me"]
}
EOF
如果我做了该步骤以后，发现docker不能正常的启动的，去掉以后正常了又。

Second：
if [[ "$OS" == "CentOS" ]];then
  yum install -y yum-utils device-mapper-persistent-data lvm2
  [[ -f /usr/bin/docker ]] || { curl -s http://elven.vip/ks/sh/c7.docker.sh |bash ; }   ##我加的安装docker的脚本。
  #yum-config-manager --add-repo http://mirrors.aliyun.com/docker-ce/linux/centos/docker-ce.repo
  yum makecache fast
  #yum -y install docker-ce
  systemctl enable docker && systemctl start docker  
fi
依照您原脚本中安装docker的repo，实际上是timeout。
http://elven.vip/ks/sh/c7.docker.sh
第二个问题已经解决。但是第一个问题，却没有搞定，麻烦告知一下解决方案，谢谢。

**Comment by wrfly** [comment]
Hi, 能把docker的启动失败日志贴一下吗, 我用虚拟机测试过OK的.

还有docker版本是多少啊

**Comment by BurlyLuo** [comment]
[root@localhost ~]# kubectl get pods -n=kube-system -o wide 
NAME                                   READY     STATUS    RESTARTS   AGE       IP              NODE
etcd-localhost.localdomain             1/1       Running   0          23s       192.168.43.10   localhost.localdomain
kube-apiserver-localhost.localdomain   1/1       Running   0          24s       192.168.43.10   localhost.localdomain
kube-scheduler-localhost.localdomain   1/1       Running   0          49s       192.168.43.10   localhost.localdomain

重新做了一下环境发现ok了。
但是对于DNS和dashboard的集成没有做上去呢。
如果把这些集成上去就好了。


这是我做的1.7.3的测试platform
NAMESPACE     NAME                                        READY     STATUS    RESTARTS   AGE       IP                NODE
kube-system   calico-etcd-3z4v2                           1/1       Running   0          2d        192.168.133.44    k8s-1
kube-system   calico-node-1w09m                           2/2       Running   1          2d        192.168.133.45    k8s-2
kube-system   calico-node-tpdkm                           2/2       Running   0          2d        192.168.133.44    k8s-1
kube-system   calico-policy-controller-1727037546-h2gst   1/1       Running   0          2d        192.168.133.44    k8s-1
kube-system   etcd-k8s-1                                  1/1       Running   0          2d        192.168.133.44    k8s-1
kube-system   heapster-84017538-l0mv7                     1/1       Running   0          2d        192.168.200.193   k8s-2
kube-system   kube-apiserver-k8s-1                        1/1       Running   0          2d        192.168.133.44    k8s-1
kube-system   kube-controller-manager-k8s-1               1/1       Running   0          2d        192.168.133.44    k8s-1
kube-system   kube-dns-2425271678-rrps9                   3/3       Running   0          2d        192.168.231.194   k8s-1
kube-system   kube-proxy-cgkds                            1/1       Running   0          2d        192.168.133.44    k8s-1
kube-system   kube-proxy-wh2rz                            1/1       Running   0          2d        192.168.133.45    k8s-2
kube-system   kube-scheduler-k8s-1                        1/1       Running   0          2d        192.168.133.44    k8s-1
kube-system   kubernetes-dashboard-3313488171-9kwpq       1/1       Running   0          2d        192.168.231.193   k8s-1
kube-system   monitoring-grafana-1500490092-824df         1/1       Running   0          2d        192.168.200.194   k8s-2
kube-system   monitoring-influxdb-1870447071-65sk6        1/1       Running   0          2d        192.168.200.195   k8s-2
